import { useEffect,useState } from "react";
import { Clock3, Plus, Send, Users } from "lucide-react";
import { campaignsApi,contactsApi,whatsappApi } from "../api";

export default function Broadcast(){
 const [campaigns,setCampaigns]=useState([]),[accounts,setAccounts]=useState([]),[contacts,setContacts]=useState([]),[open,setOpen]=useState(false),[error,setError]=useState("");
 const [form,setForm]=useState({name:"",body:"",accountId:"",contactIds:[]});
 const load=async()=>{try{const [c,a,k]=await Promise.all([campaignsApi.list(),whatsappApi.list(),contactsApi.list()]);setCampaigns(c.data);setAccounts(a.data);setContacts(k.data.filter(x=>x.optedIn))}catch(e){setError(e.response?.data?.error||"Gagal memuat campaign.")}};
 useEffect(()=>{load()},[]);
 const toggle=id=>setForm(f=>({...f,contactIds:f.contactIds.includes(id)?f.contactIds.filter(x=>x!==id):[...f.contactIds,id]}));
 const submit=async e=>{e.preventDefault();setError("");try{await campaignsApi.create(form);setOpen(false);setForm({name:"",body:"",accountId:"",contactIds:[]});load()}catch(e){setError(e.response?.data?.error||"Gagal membuat campaign.")}};
 return <div><div className="welcome"><div><span className="eyebrow">CAMPAIGNS</span><h1>Broadcast</h1><p>Buat campaign menggunakan contact yang sudah opt-in.</p></div><button className="primary-btn small" onClick={()=>setOpen(true)}><Plus size={17}/> New Broadcast</button></div>
 {open&&<div className="modal-backdrop"><form className="modal campaign-modal" onSubmit={submit}><h2>Create Broadcast</h2><p>Campaign tanpa jadwal akan langsung masuk queue.</p>{error&&<div className="form-error">{error}</div>}<label>Nama Campaign<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Promo akhir bulan"/></label><label>WhatsApp Account<select required value={form.accountId} onChange={e=>setForm({...form,accountId:e.target.value})}><option value="">Pilih account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} — {a.phone}</option>)}</select></label><label>Pesan<textarea required rows="5" value={form.body} onChange={e=>setForm({...form,body:e.target.value})} placeholder="Halo {nama}, ..."/></label><label>Pilih Contact ({form.contactIds.length})<div className="contact-picker">{contacts.map(c=><label className="check-row" key={c.id}><input type="checkbox" checked={form.contactIds.includes(c.id)} onChange={()=>toggle(c.id)}/><span>{c.name} — {c.phone}</span></label>)}{!contacts.length&&<span className="muted-note">Belum ada contact opt-in.</span>}</div></label><div className="modal-actions"><button type="button" className="outline-btn" onClick={()=>setOpen(false)}>Cancel</button><button disabled={!accounts.length||!contacts.length||!form.contactIds.length} className="primary-btn">Create & Queue</button></div></form></div>}
 <div className="panel"><div className="table-head"><div>Campaign</div><div>Account</div><div>Status</div><div>Created</div></div>{campaigns.map(c=><div className="table-row" key={c.id}><div className="campaign"><div className="list-icon"><Send size={16}/></div><strong>{c.name}</strong></div><div>{c.account?.name||"-"} <span className="count-badge">{c._count?.messages||0}</span></div><div><span className={`status-pill ${c.status==="COMPLETED"?"success":c.status==="FAILED"?"warning":"muted"}`}>{c.status}</span></div><div><Clock3 size={15}/> {new Date(c.createdAt).toLocaleString("id-ID")}</div></div>)}{!campaigns.length&&<div className="empty">Belum ada campaign.</div>}</div></div>
}